[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Jito Docs"
authors = [{name = "mdr0id", email = "marshall@jito.wtf"}]
dynamic = ["version", "description"]
